// Install REST Client VSCode extension to use this file for testing
@host=http://localhost:3000
// Using npm run start
get {{ host }}/posts/

###
GET {{ host }}/posts?title=json-server&author=typicode

### 
get {{ host }}/comments

###
GET {{host}}/comments?author.name=Casiano

### 
get {{ host }}/echo?message=hello

### 
post {{ host }}/posts
Content-Type: application/json

{ 
  "id": 2, 
  "title": "Spanish Queen", 
  "author": "Ferdinand" 
}

// testing npm run gh. The db is gh-config.json
###
GET {{ host }}/aliases
Content-Type: application/json

###
GET {{ host }}/extensions
Content-Type: application/json